// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWLrLXP7uIMKag8nSkQnuk-879lSYukpg',
    appId: '1:22206943093:web:8ce552be449db9a9774d3c',
    messagingSenderId: '22206943093',
    projectId: 'kenongo-task',
    authDomain: 'kenongo-task.firebaseapp.com',
    storageBucket: 'kenongo-task.firebasestorage.app',
    measurementId: 'G-GLDSYK5W3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcByAZ6ZccSVWCyiS5wD5M30u0bPL_A4',
    appId: '1:666289518279:android:e33fcb1c499ed34909f0e2',
    messagingSenderId: '666289518279',
    projectId: 'kenongo-task-e6a5a',
    storageBucket: 'kenongo-task-e6a5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTxg8lF7zhqvOyDrw9YJm2hQLOaRhELUM',
    appId: '1:22206943093:ios:6d160ceb5ac3cda0774d3c',
    messagingSenderId: '22206943093',
    projectId: 'kenongo-task',
    storageBucket: 'kenongo-task.firebasestorage.app',
    iosBundleId: 'com.example.kenongotask2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTxg8lF7zhqvOyDrw9YJm2hQLOaRhELUM',
    appId: '1:22206943093:ios:6d160ceb5ac3cda0774d3c',
    messagingSenderId: '22206943093',
    projectId: 'kenongo-task',
    storageBucket: 'kenongo-task.firebasestorage.app',
    iosBundleId: 'com.example.kenongotask2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWLrLXP7uIMKag8nSkQnuk-879lSYukpg',
    appId: '1:22206943093:web:03bf7e3b82eedc75774d3c',
    messagingSenderId: '22206943093',
    projectId: 'kenongo-task',
    authDomain: 'kenongo-task.firebaseapp.com',
    storageBucket: 'kenongo-task.firebasestorage.app',
    measurementId: 'G-QP5M3QN2V3',
  );

}